/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burgerkingjuancarlos;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author PC10
 */
public class InterfazBurguer extends javax.swing.JFrame {
    /**
     * Creates new form InterfazBurguer
     */
    public InterfazBurguer() {
        //FondoPanel fondo = new FondoPanel();
        initComponents();
         CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
         c1.show(this.panelPrincipal, "cardMenuPrincipal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        PantallaPedido = new PanelConFondo("/imagenes/logoMenu.png");
        lblNuevoProducto = new javax.swing.JLabel();
        btnVolverMenuPedido = new javax.swing.JButton();
        btnPlatosPrinc = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        btnPostres = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCestaProductos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        MenuPrincipal = new PanelConFondo("/imagenes/logoMenu.png");
        btnPedir = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        lblNuevoProducto.setBackground(new java.awt.Color(255, 0, 204));
        lblNuevoProducto.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblNuevoProducto.setForeground(new java.awt.Color(0, 102, 0));
        lblNuevoProducto.setText("nuevo pedido");

        btnVolverMenuPedido.setText("Volver al menú");
        btnVolverMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuPedidoActionPerformed(evt);
            }
        });

        btnPlatosPrinc.setText("Platos Principales");

        btnBebidas.setText("Bebidas");

        btnPostres.setText("Postres");

        btnMenu.setText("Menús");

        jScrollPane1.setViewportView(listaCestaProductos);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Resumen Pedido");

        btnEliminarProducto.setText("Eliminar Producto");

        btnFinalizarPedido.setText("Finalizar Pedido");

        javax.swing.GroupLayout PantallaPedidoLayout = new javax.swing.GroupLayout(PantallaPedido);
        PantallaPedido.setLayout(PantallaPedidoLayout);
        PantallaPedidoLayout.setHorizontalGroup(
            PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVolverMenuPedido))
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                        .addComponent(btnPlatosPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(btnPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 44, Short.MAX_VALUE))))
                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                        .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(lblNuevoProducto))
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PantallaPedidoLayout.setVerticalGroup(
            PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                .addComponent(lblNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlatosPrinc)
                    .addComponent(btnBebidas)
                    .addComponent(btnPostres)
                    .addComponent(btnMenu))
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                        .addComponent(btnEliminarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizarPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnVolverMenuPedido))
        );

        panelPrincipal.add(PantallaPedido, "cardPantallaPedido");

        MenuPrincipal.setToolTipText("");

        btnPedir.setText("Nuevo Pedido");
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });

        btnAdministrador.setText("Administrador");

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnPedir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnAdministrador)
                .addGap(193, 193, 193))
        );

        panelPrincipal.add(MenuPrincipal, "cardMenuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuPedidoActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardMenuPrincipal");
    }//GEN-LAST:event_btnVolverMenuPedidoActionPerformed

    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardPantallaPedido");
    }//GEN-LAST:event_btnPedirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBurguer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel PantallaPedido;
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnPlatosPrinc;
    private javax.swing.JButton btnPostres;
    private javax.swing.JButton btnVolverMenuPedido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNuevoProducto;
    private javax.swing.JList<String> listaCestaProductos;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    
// Este método sirve para poner de fondo una imagen en un JPanel. 
    public class PanelConFondo extends JPanel {
    private Image imagen;

  
   public PanelConFondo(String rutaImagen) {
        try {
            // Cargar la imagen desde el classpath
            java.net.URL resource = getClass().getResource(rutaImagen);
            if (resource != null) {
                imagen = new ImageIcon(resource).getImage();
            } else {
                System.err.println("Recurso no encontrado: " + rutaImagen);
            }
        } catch (Exception ex) {
            System.err.println("Error al cargar la imagen: " + ex.getMessage());
        }
    }

    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Dibujar la imagen de fondo
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
}

