/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burgerkingjuancarlos;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC10
 */
public class InterfazBurguer extends javax.swing.JFrame {
    /**
     * Creates new form InterfazBurguer
     */
     Hamburgueseria urjc = new Hamburgueseria();
     DefaultListModel listaPlatosPrincipales = new DefaultListModel();
    
    public InterfazBurguer() {
        initComponents();
         CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
         c1.show(this.panelPrincipal, "cardMenuPrincipal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        PlatosPrincipalesAdmin = new javax.swing.JPanel();
        lblTituloPlatosPrincipales = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPlatosPrincipalesAdmin = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarPlato = new javax.swing.JButton();
        btnAnadirProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePlato = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtImagenPlato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioPlato = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTiempoPlato = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoPlatoAdmin = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnVolverPlatosPrincipales = new javax.swing.JButton();
        lblFotoPlatoPrincipal = new javax.swing.JLabel();
        ProductosAdministrador = new javax.swing.JPanel();
        lblTituloProductos = new javax.swing.JLabel();
        btnPlatosPrincipales = new javax.swing.JButton();
        btnBebidasProductos = new javax.swing.JButton();
        btnPostresProductos = new javax.swing.JButton();
        btnMenusProductos = new javax.swing.JButton();
        btnVolverProductos = new javax.swing.JButton();
        Administrador = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVolverAdministrador = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnCopiaSeguridad = new javax.swing.JButton();
        btnRestaurarDatos = new javax.swing.JButton();
        InicioSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordAdministrador = new javax.swing.JPasswordField();
        lblContraseña = new javax.swing.JLabel();
        btnEntrarAdmin = new javax.swing.JButton();
        PantallaPedido = new PanelConFondo("/imagenes/logoMenu.png");
        lblNuevoProducto = new javax.swing.JLabel();
        btnVolverMenuPedido = new javax.swing.JButton();
        btnPlatosPrinc = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        btnPostres = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCestaProductos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        MenuPrincipal = new PanelConFondo("/imagenes/logoMenu.png");
        btnPedir = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        lblTituloPlatosPrincipales.setFont(new java.awt.Font("Bernard MT Condensed", 2, 24)); // NOI18N
        lblTituloPlatosPrincipales.setText("Platos Principales");

        listaPlatosPrincipalesAdmin.setModel(listaPlatosPrincipales);
        listaPlatosPrincipalesAdmin.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPlatosPrincipalesAdminValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaPlatosPrincipalesAdmin);

        jLabel3.setText("Lista de Platos Principales");

        btnEliminarPlato.setText("Eliminar producto seleccionado");
        btnEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatoActionPerformed(evt);
            }
        });

        btnAnadirProducto.setText("Añadir/Modificar");
        btnAnadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirProductoActionPerformed(evt);
            }
        });

        jLabel5.setText("Añadir/Modificar Productos");

        jLabel6.setText("Nombre");

        jLabel7.setText("Imagen");

        jLabel8.setText("Precio");

        jLabel9.setText("Tiempo Elaboración");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        infoPlatoAdmin.setColumns(20);
        infoPlatoAdmin.setRows(5);
        jScrollPane3.setViewportView(infoPlatoAdmin);

        jLabel11.setText("Información del producto");

        btnVolverPlatosPrincipales.setText("Volver");
        btnVolverPlatosPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverPlatosPrincipalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlatosPrincipalesAdminLayout = new javax.swing.GroupLayout(PlatosPrincipalesAdmin);
        PlatosPrincipalesAdmin.setLayout(PlatosPrincipalesAdminLayout);
        PlatosPrincipalesAdminLayout.setHorizontalGroup(
            PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlatosPrincipalesAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverPlatosPrincipales))
            .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarPlato)
                            .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                                .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(lblFotoPlatoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblTituloPlatosPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtImagenPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtTiempoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(116, 116, 116))
                    .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        PlatosPrincipalesAdminLayout.setVerticalGroup(
            PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPlatosPrincipales)
                .addGap(18, 18, 18)
                .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addGroup(PlatosPrincipalesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarPlato))
                            .addComponent(lblFotoPlatoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PlatosPrincipalesAdminLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImagenPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnadirProducto))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnVolverPlatosPrincipales)
                .addContainerGap())
        );

        panelPrincipal.add(PlatosPrincipalesAdmin, "cardPlatosPrincipalesAdmin");

        lblTituloProductos.setFont(new java.awt.Font("Bernard MT Condensed", 2, 24)); // NOI18N
        lblTituloProductos.setText("PRODUCTOS");

        btnPlatosPrincipales.setText("Platos Principales");
        btnPlatosPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatosPrincipalesActionPerformed(evt);
            }
        });

        btnBebidasProductos.setText("Bebidas");
        btnBebidasProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasProductosActionPerformed(evt);
            }
        });

        btnPostresProductos.setText("Postres");

        btnMenusProductos.setText("Menús");

        btnVolverProductos.setText("Volver");
        btnVolverProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductosAdministradorLayout = new javax.swing.GroupLayout(ProductosAdministrador);
        ProductosAdministrador.setLayout(ProductosAdministradorLayout);
        ProductosAdministradorLayout.setHorizontalGroup(
            ProductosAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosAdministradorLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(ProductosAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProductosAdministradorLayout.createSequentialGroup()
                        .addComponent(lblTituloProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductosAdministradorLayout.createSequentialGroup()
                        .addGroup(ProductosAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBebidasProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlatosPrincipales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPostresProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenusProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductosAdministradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverProductos)
                .addContainerGap())
        );
        ProductosAdministradorLayout.setVerticalGroup(
            ProductosAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloProductos)
                .addGap(69, 69, 69)
                .addComponent(btnPlatosPrincipales)
                .addGap(26, 26, 26)
                .addComponent(btnBebidasProductos)
                .addGap(27, 27, 27)
                .addComponent(btnPostresProductos)
                .addGap(28, 28, 28)
                .addComponent(btnMenusProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnVolverProductos)
                .addContainerGap())
        );

        panelPrincipal.add(ProductosAdministrador, "cardProductosAdministrador");

        jLabel4.setFont(new java.awt.Font("Bernard MT Condensed", 2, 24)); // NOI18N
        jLabel4.setText("ADMINISTRADOR");

        btnVolverAdministrador.setText("Volver");
        btnVolverAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAdministradorActionPerformed(evt);
            }
        });

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnVentas.setText("Ventas");

        btnCopiaSeguridad.setText("Copia de seguridad");

        btnRestaurarDatos.setText("Restaurar datos");

        javax.swing.GroupLayout AdministradorLayout = new javax.swing.GroupLayout(Administrador);
        Administrador.setLayout(AdministradorLayout);
        AdministradorLayout.setHorizontalGroup(
            AdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdministradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverAdministrador)
                .addContainerGap())
            .addGroup(AdministradorLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(AdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCopiaSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestaurarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        AdministradorLayout.setVerticalGroup(
            AdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(99, 99, 99)
                .addComponent(btnProductos)
                .addGap(18, 18, 18)
                .addComponent(btnVentas)
                .addGap(18, 18, 18)
                .addComponent(btnCopiaSeguridad)
                .addGap(18, 18, 18)
                .addComponent(btnRestaurarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(btnVolverAdministrador))
        );

        panelPrincipal.add(Administrador, "cardAdministrador");

        InicioSesion.setBackground(new java.awt.Color(0, 204, 204));
        InicioSesion.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 3, 24)); // NOI18N
        jLabel1.setText("Inicio de sesión");

        passwordAdministrador.setText("jPasswordField1");

        lblContraseña.setText("Indique la contraseña.");

        btnEntrarAdmin.setText("Entrar");
        btnEntrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioSesionLayout = new javax.swing.GroupLayout(InicioSesion);
        InicioSesion.setLayout(InicioSesionLayout);
        InicioSesionLayout.setHorizontalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InicioSesionLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEntrarAdmin)
                            .addGroup(InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        InicioSesionLayout.setVerticalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEntrarAdmin)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        panelPrincipal.add(InicioSesion, "cardInicioSesion");

        lblNuevoProducto.setBackground(new java.awt.Color(255, 0, 204));
        lblNuevoProducto.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblNuevoProducto.setForeground(new java.awt.Color(0, 102, 0));
        lblNuevoProducto.setText("nuevo pedido");

        btnVolverMenuPedido.setText("Volver al menú");
        btnVolverMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuPedidoActionPerformed(evt);
            }
        });

        btnPlatosPrinc.setText("Platos Principales");

        btnBebidas.setText("Bebidas");

        btnPostres.setText("Postres");

        btnMenu.setText("Menús");

        jScrollPane1.setViewportView(listaCestaProductos);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Resumen Pedido");

        btnEliminarProducto.setText("Eliminar Producto");

        btnFinalizarPedido.setText("Finalizar Pedido");

        javax.swing.GroupLayout PantallaPedidoLayout = new javax.swing.GroupLayout(PantallaPedido);
        PantallaPedido.setLayout(PantallaPedidoLayout);
        PantallaPedidoLayout.setHorizontalGroup(
            PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVolverMenuPedido))
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                        .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(lblNuevoProducto))
                            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PantallaPedidoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPlatosPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        PantallaPedidoLayout.setVerticalGroup(
            PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPedidoLayout.createSequentialGroup()
                .addComponent(lblNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlatosPrinc)
                    .addComponent(btnBebidas)
                    .addComponent(btnPostres)
                    .addComponent(btnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PantallaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnVolverMenuPedido))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaPedidoLayout.createSequentialGroup()
                        .addComponent(btnEliminarProducto)
                        .addGap(117, 117, 117)
                        .addComponent(btnFinalizarPedido)
                        .addGap(69, 69, 69))))
        );

        panelPrincipal.add(PantallaPedido, "cardPantallaPedido");

        MenuPrincipal.setToolTipText("");

        btnPedir.setText("Nuevo Pedido");
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });

        btnAdministrador.setText("Administrador");
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(btnPedir)
                .addGap(101, 101, 101)
                .addComponent(btnAdministrador)
                .addGap(193, 193, 193))
        );

        panelPrincipal.add(MenuPrincipal, "cardMenuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuPedidoActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardMenuPrincipal");
    }//GEN-LAST:event_btnVolverMenuPedidoActionPerformed

    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardPantallaPedido");
    }//GEN-LAST:event_btnPedirActionPerformed

    private void btnEntrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarAdminActionPerformed
        // Compruebo si la contraseña es correcta: 
        if (this.passwordAdministrador.getText().equals(ModoAdministrador.contraseña)){
            //Si es igual, paso de panel: 
            CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
            c1.show(this.panelPrincipal, "cardAdministrador");
            
        }else{
            // Mostrar pantalla emergente con JOptionPane
                JOptionPane.showMessageDialog(null, 
                "Contraseña Incorrecta", 
                "Pruebe otra vez.", 
                JOptionPane.ERROR_MESSAGE);
     
        }
        
        
    }//GEN-LAST:event_btnEntrarAdminActionPerformed

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
            c1.show(this.panelPrincipal, "cardInicioSesion");
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnVolverAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAdministradorActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
            c1.show(this.panelPrincipal, "cardMenuPrincipal");
    }//GEN-LAST:event_btnVolverAdministradorActionPerformed

    private void btnBebidasProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBebidasProductosActionPerformed

    private void btnVolverProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverProductosActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardAdministrador");
    }//GEN-LAST:event_btnVolverProductosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardProductosAdministrador");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPlatosPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatosPrincipalesActionPerformed
        // TODO add your handling code here:
        //Cargo la lista de productos y cambio de pantalla.
        this.listaPlatosPrincipales.removeAllElements();
        CatalogoProductos catalogo = urjc.getCatalogo();
        for (Principal plato: catalogo.getPlatosPrincipales()){
            listaPlatosPrincipales.addElement(plato.getNombre());
        }
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardPlatosPrincipalesAdmin");
        
    }//GEN-LAST:event_btnPlatosPrincipalesActionPerformed

    private void btnEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatoActionPerformed
        // TODO add your handling code here:
        //Aquí, cojo el catálogo de productos.
        CatalogoProductos catalogo = urjc.getCatalogo();
        //Busco el elemento seleccionado: 
        String nombreEliminar = this.listaPlatosPrincipalesAdmin.getSelectedValue();
        //Un método que, dado el nombre de un producto, lo elimine del catálogo.
        Producto productoEliminar = catalogo.buscarProducto(nombreEliminar);
        catalogo.eliminarProducto(productoEliminar);
        //Una vez eliminado, elimino el elemento de la lista. 
        listaPlatosPrincipales.removeElement(nombreEliminar);
        
        
    }//GEN-LAST:event_btnEliminarPlatoActionPerformed

    private void btnAnadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirProductoActionPerformed
        // TODO add your handling code here:
        
        //Voy a coger los elementos, los cargo en un objeto de la clase Principal, lo añado al catálogo, y muestro el catálogo.
        
        String nombrePlato = this.txtNombrePlato.getText();
        String imagenPlato = this.txtImagenPlato.getText();
        int precio = Integer.parseInt(this.txtPrecioPlato.getText());
        int tiempo = Integer.parseInt(this.txtTiempoPlato.getText());
        
        //Ahora creo el producto. 
        Producto plato = new Principal(nombrePlato, imagenPlato, precio, tiempo); 
        //Cargo el catálogo y lo añado: 
        CatalogoProductos catalogo = urjc.getCatalogo();
        catalogo.agregarProducto(plato);
        //Lo añado a la lista: 
        this.listaPlatosPrincipales.addElement(nombrePlato);
    }//GEN-LAST:event_btnAnadirProductoActionPerformed

    private void btnVolverPlatosPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverPlatosPrincipalesActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) this.panelPrincipal.getLayout();
        c1.show(this.panelPrincipal, "cardProductosAdministrador");
    }//GEN-LAST:event_btnVolverPlatosPrincipalesActionPerformed

    private void listaPlatosPrincipalesAdminValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPlatosPrincipalesAdminValueChanged
        // TODO add your handling code here:
        //Quiero que, si lo seleccionas, en el frame de abajo salgan sus datos. Para ello: 
        if (!this.listaPlatosPrincipales.isEmpty()){
             String elementoSeleccionado = this.listaPlatosPrincipalesAdmin.getSelectedValue();
            //Ahora, busco el producto en el catálogo: 
            CatalogoProductos catalogo = urjc.getCatalogo();
            Producto producto = catalogo.buscarProducto(elementoSeleccionado);
            // Una vez encontrado, cargo su info: 
            this.infoPlatoAdmin.setText(producto.toString());
            //Cargo su foto. 
            String ruta = "/imagenes/"+producto.getImagen();
            ImageIcon imagen = new ImageIcon(getClass().getResource(ruta)); 
            this.lblFotoPlatoPrincipal.setIcon(imagen);
        }else{
            this.infoPlatoAdmin.setText("NO hay platos principales en el catálogo.");
            this.lblFotoPlatoPrincipal.setIcon(null);
        }
       
    }//GEN-LAST:event_listaPlatosPrincipalesAdminValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBurguer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBurguer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Administrador;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel PantallaPedido;
    private javax.swing.JPanel PlatosPrincipalesAdmin;
    private javax.swing.JPanel ProductosAdministrador;
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnAnadirProducto;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnBebidasProductos;
    private javax.swing.JButton btnCopiaSeguridad;
    private javax.swing.JButton btnEliminarPlato;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEntrarAdmin;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenusProductos;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnPlatosPrinc;
    private javax.swing.JButton btnPlatosPrincipales;
    private javax.swing.JButton btnPostres;
    private javax.swing.JButton btnPostresProductos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRestaurarDatos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVolverAdministrador;
    private javax.swing.JButton btnVolverMenuPedido;
    private javax.swing.JButton btnVolverPlatosPrincipales;
    private javax.swing.JButton btnVolverProductos;
    private javax.swing.JTextArea infoPlatoAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblFotoPlatoPrincipal;
    private javax.swing.JLabel lblNuevoProducto;
    private javax.swing.JLabel lblTituloPlatosPrincipales;
    private javax.swing.JLabel lblTituloProductos;
    private javax.swing.JList<String> listaCestaProductos;
    private javax.swing.JList<String> listaPlatosPrincipalesAdmin;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField passwordAdministrador;
    private javax.swing.JTextField txtImagenPlato;
    private javax.swing.JTextField txtNombrePlato;
    private javax.swing.JTextField txtPrecioPlato;
    private javax.swing.JTextField txtTiempoPlato;
    // End of variables declaration//GEN-END:variables

    
// Este método sirve para poner de fondo una imagen en un JPanel. 
    public class PanelConFondo extends JPanel {
    private Image imagen;

  
   public PanelConFondo(String rutaImagen) {
        try {
            // Cargar la imagen desde el classpath
            java.net.URL resource = getClass().getResource(rutaImagen);
            if (resource != null) {
                imagen = new ImageIcon(resource).getImage();
            } else {
                System.err.println("Recurso no encontrado: " + rutaImagen);
            }
        } catch (Exception ex) {
            System.err.println("Error al cargar la imagen: " + ex.getMessage());
        }
    }

    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Dibujar la imagen de fondo
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
}

